### ISSUE TITLE
expose pma in subpath

### ISSUE THREAD

**Issue by fragolinux** [mhzawadi/phpmyadmin#26]
hi, is it possible to expose pma not on the root, but in a subpath?
what i'd like is having http://ip with standard nginx and php support, and pma on http:/ip/pma
thanks!

**Comment by mhzawadi** [comment]
Hello 👋🏼 

Will have a look at what I can do, in the mean time you could inject your own nginx config or put a proxy server in front.

**Comment by mhzawadi** [comment]
I've had a look and not sure I can change the config to add path, but I have pushed a compose file that would allow you to use a path via traefik. That would be a better way to route to containers that run from the root of the URL.

https://github.com/mhzawadi/phpmyadmin/blob/master/docker-compose-path.yml

**Comment by mhzawadi** [comment]
if you still have issues please reopen this
