### ISSUE TITLE
Nginx invalid number of arguments "server_name"

### ISSUE THREAD

**Issue by dcedjiayi** [mhzawadi/phpmyadmin#3]
Hello, I encountered this error when I just pull the image and run it without additional commands in my Dockerfile.

`invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/site.conf:3`

I am using v5.0.2.1 on an ARM64 platform.

**Comment by mhzawadi** [comment]
Hi @dcedjiayi 

It looks like your not setting the HOST_URL when you book your image, when you run `docker run --name myadmin -d --link mysql_db_server:db -p 8080:80 -e HOST_URL=127.0.0.1 mhzawadi/phpmyadmin` do you get a startup?

**Comment by dcedjiayi** [comment]
Hello @mhzawadi 

I am sorry but I forgotten to mention that I used `docker-compose up` to bring up the containers. I did not run individual commands to bring up the containers individually.

**Comment by mhzawadi** [comment]
Hi @dcedjiayi,

Could you upload your compose file to have a look at please?

**Comment by dcedjiayi** [comment]
Hello, here is the part of my compose file that handles phpmyadmin part.
`    pma:
        build:
            context: ./pma
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: somepassword
        volumes:
            - webroot:/var/www/html
            - pma_source:/usr/src/phpmyadmin
`

**Comment by mhzawadi** [comment]
Morning @dcedjiayi ,
Have just build a new version of my image, you now dont need the HOST_URL. Can you try your build now please

**Comment by mhzawadi** [comment]
Hi @dcedjiayi if you still have issues please reopen this
